name: aerell_volume_control
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  material_color_generator: ^1.1.0
  package_info_plus: ^3.0.3
  provider: ^6.0.5
  shared_preferences: ^2.0.18
  volume: ^1.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
flutter_intl:
  enabled: true
